update action

diff --git a/.github/workflows/build-index.yml b/.github/workflows/build-index.yml
--- a/.github/workflows/build-index.yml
+++ b/.github/workflows/build-index.yml
@@ -47,11 +47,16 @@ jobs:
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add index.xml
           
-          if git diff --staged --quiet; then
-            echo "No changes detected in index.xml."
+          if [ -f index.xml ]; then
+            git add index.xml
+            if git diff --staged --quiet; then
+              echo "No changes detected in index.xml."
+            else
+              git commit -m "chore: rebuild ReaPack index.xml"
+              git push
+            fi
           else
-            git commit -m "chore: rebuild ReaPack index.xml"
-            git push
+            echo "Error: index.xml was not generated by reapack-index."
+            exit 1
           fi
